train: false
work_dir: ""
seed: 234

use_wandb: false
wandb_run_id: null
wandb_project: ""

num_workers: 1
batch_size: 1
test_num_workers: 4
test_batch_size: 1

# EXPERIMENT
finetune: false
from_scratch: false
ft_rate: 1.0
limited_label_train: 1
limited_label_val: 1
limited_label_strategy: stratified
stratification_bins: 3
data_replicate: 1
use_final_ckpt: false

ckpt_dir: /home/nisla/ShapingFT/results_class_hier1/20260126_144727_46d6d8_utae_encoder_seg_utae_fuelmaphier1/

defaults:
  - task: segmentation
  - dataset: fuelmap
  - encoder: utae_encoder
  - decoder: seg_utae
  - criterion: weighted_cross_entropy
  - lr_scheduler: multi_step_lr
  - optimizer: adamw
  - _self_