train: true
work_dir: ""
seed: 234
use_wandb: true
wandb_run_id: null
wandb_project: "Utae-FuelMap-Classifier_Hier2_MT"

# TRAINING
num_workers: 4
batch_size: 2

test_num_workers: 4
test_batch_size: 1

# EXPERIMENT
finetune: true
from_scratch: true
ft_rate: 1.0
ckpt_dir: null
limited_label_train: 1
limited_label_val: 1
limited_label_strategy: stratified  # Options: stratified, oversampled, random
stratification_bins: 3 #  number of bins for stratified sampling, only for stratified
data_replicate: 1
use_final_ckpt: false


defaults:
  - task: segmentation
  - dataset: fuelmaphier2_MT
  - encoder: utae_encoder
  - decoder: seg_utae
  - preprocessing: ???
  - criterion: weighted_cross_entropy
  - lr_scheduler: multi_step_lr
  - optimizer: adamw
  - _self_ 
